// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmKIJYZHJmHV9W9EKJu1iT9LiCPXTzRkc',
    appId: '1:119689375823:android:9da6616c28f4a07bf23a3a',
    messagingSenderId: '119689375823',
    projectId: 'mynotes-c3b1a',
    storageBucket: 'mynotes-c3b1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWyfZQxiHr_5Yqgal-JGaVwacWCujzvKA',
    appId: '1:119689375823:ios:c9d05f0856bb954df23a3a',
    messagingSenderId: '119689375823',
    projectId: 'mynotes-c3b1a',
    storageBucket: 'mynotes-c3b1a.appspot.com',
    iosClientId: '119689375823-aupo365o1q2i7um4c51eb6n2tcvmrefg.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuff.mynotes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBa0vK5INWhOBKGaYW9ieHPYtkWdZZYdk',
    appId: '1:119689375823:web:cef26806155f222cf23a3a',
    messagingSenderId: '119689375823',
    projectId: 'mynotes-c3b1a',
    authDomain: 'mynotes-c3b1a.firebaseapp.com',
    storageBucket: 'mynotes-c3b1a.appspot.com',
    measurementId: 'G-8TT3BSG2PR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWyfZQxiHr_5Yqgal-JGaVwacWCujzvKA',
    appId: '1:119689375823:ios:c9d05f0856bb954df23a3a',
    messagingSenderId: '119689375823',
    projectId: 'mynotes-c3b1a',
    storageBucket: 'mynotes-c3b1a.appspot.com',
    iosClientId: '119689375823-aupo365o1q2i7um4c51eb6n2tcvmrefg.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuff.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBa0vK5INWhOBKGaYW9ieHPYtkWdZZYdk',
    appId: '1:119689375823:web:b9f503a35478f57ef23a3a',
    messagingSenderId: '119689375823',
    projectId: 'mynotes-c3b1a',
    authDomain: 'mynotes-c3b1a.firebaseapp.com',
    storageBucket: 'mynotes-c3b1a.appspot.com',
    measurementId: 'G-FZ9RR4XW6W',
  );

}